### ISSUE TITLE
visualstudio2015community choco package fails due to generic msi error 1603

### ISSUE THREAD

**Issue by Mjimenez01** [jberezanski/ChocolateyPackages#104]
After applying the most recent windows updates, I keep getting the following error when attempting to install using the following command:
choco install visualstudio2015community -y --norestart --quiet --execution-timeout 9999

Error message:
"""
WARNING: Generic MSI Error. This is a local environment error, not an issue with a package or the MSI itself - it could mean a pending reboot is necessary prior to install or something else (like the same version is already installed). Please see MSI log if available. If not, try again adding '--install-arguments="'/l*v c:\VisualStudio2015Community_msi_install.log'"'. Then search the MSI Log for "Return Value 3" and look above that for the error.
ERROR: Running ["C:\Users\michaelj\AppData\Local\Temp\chocolatey\VisualStudio2015Community\2015.03.03\vs_community.exe" /Quiet /NoRestart /Log C:\Users\michaelj\AppData\Local\Temp\chocolatey\vs.log ] was not successful. Exit code was '1603'. Exit code indicates the following: Generic MSI Error. This is a local environment error, not an issue with a package or the MSI itself - it could mean a pending reboot is necessary prior to install or something else (like the same version is already installed). Please see MSI log if available. If not, try again adding '--install-arguments="'/l*v c:\VisualStudio2015Community_msi_install.log'"'. Then search the MSI Log for "Return Value 3" and look above that for the error..
visualstudio2015community can be automatically uninstalled.
The install of visualstudio2015community was NOT successful.
Error while running 'C:\ProgramData\chocolatey\lib\VisualStudio2015Community\Tools\ChocolateyInstall.ps1'.
See log for details.

Chocolatey installed 0/1 packages. 1 packages failed.
See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).

Failures
- visualstudio2015community (exited 1603) - Error while running 'C:\ProgramData\chocolatey\lib\VisualStudio2015Community\Tools\ChocolateyInstall.ps1'.
See log for details.
"""
Any ideas how this can be fixed? Its important to note that this only started happening recently, I have restarted after all updates and also do not have the packages already installed on my machine and have gotten the error message on multiple machines running windows 10 and windows server 2019 R2 which both previously worked.

In addition, I have noticed that sometimes I will get the following from within the vs.log file:
"""
Detected related package: {19E8AE59-4D4A-3534-B567-6CC08FA4102E}, scope: PerMachine, version: 4.5.51651.0, language: 0 operation: Downgrade OR
Detected related package: {2EC26D34-FB67-4C58-AC20-235697551222}, scope: PerMachine, version: 10.0.3802.0, language: 0 operation: Downgrade OR
Detected related package: {09645C4C-3570-8804-9ED6-C3C335679287}, scope: PerMachine, version: 10.1.19041.1, language: 0 operation: Downgrade
"""
To try and fix this, I have followed some forums advice to go into the registry and lower the version number for these values. A subsequent run still results in the exact same error message just without the previous errors. Running the command on windows server 2019 with only git installed results in the same error but this time no downgrades are detected and it still fails. Here is the vs.log file from my windows server 2019 R2 machine that only has git installed: 
[vs_2015_msi_error_log.txt](https://github.com/jberezanski/ChocolateyPackages/files/6387731/vs_2015_msi_error_log.txt)
Thanks in advance for your help.

**Comment by jberezanski** [comment]
I'm afraid I don't see anything of value in that log file, except the information that a child process is invoked and it exits with code 1603. I'm pretty sure there should be more log files in the C:\Users\<user>\AppData\Local\Temp\chocolatey directory (speaking from experience, their names will probably start with "dd_"). Please see if you can locate them.

**Comment by jberezanski** [comment]
I've done a quick check myself and I can see the problem, too.
There are indeed additional log files and inside them one can see several download errors - the installer is trying to download components from urls which no longer work. Example:

```
[1BD4:0020][2021-04-27T03:42:58]i338: Acquiring package: vs_vshubcore, payload: vs_vshubcore, download from: http://go.microsoft.com/fwlink/?LinkId=562603&clcid=0x409
[1BD4:0020][2021-04-27T03:42:58]e000: Error 0x80070002: Failed to send request to URL: http://go.microsoft.com/fwlink/?LinkId=562603&clcid=0x409
[1BD4:0020][2021-04-27T03:42:58]e000: Error 0x80070002: Failed to connect to URL: http://go.microsoft.com/fwlink/?LinkId=562603&clcid=0x409
[1BD4:0020][2021-04-27T03:42:58]e000: Error 0x80070002: Failed to get size and time for URL: http://go.microsoft.com/fwlink/?LinkId=562603&clcid=0x409
[1BD4:0020][2021-04-27T03:42:58]e000: Error 0x80070002: Failed attempt to download URL: 'http://go.microsoft.com/fwlink/?LinkId=562603&clcid=0x409' to: 'C:\Users\Admin\AppData\Local\Temp\chocolatey\{4f075c79-8ee3-4c85-9408-828736d1f7f3}\vs_vshubcore'
[1BD4:0020][2021-04-27T03:42:58]w343: Prompt for source of package: vs_vshubcore, payload: vs_vshubcore, path: C:\Users\Admin\AppData\Local\Temp\chocolatey\20210427_034049_{4312D170-FE25-36BF-B5E6-0A87C44B7EF0}\packages\vs_vshub\VsHub_Core.msi
```

I tried to download the latest VS 2015 installer from Microsoft, thinking that maybe it would contain updated urls. The installers do not seem to be freely available; I had to log on to my MSDN subscription, as instructed on https://visualstudio.microsoft.com/vs/older-downloads/. I downloaded "Visual Studio Professional 2015 with Update 3" - published on 2016-06-27 and tried to install VS 2015 in the normal, interactive way (clicking through the GUI). The installer sadly informed me that it was unable to download some installation files - same kind of errors visible in the log file.

So it appears that Microsoft removed several files from their download servers, breaking VS 2015 installation. I guess we can't do anything except wait for MS to fix this.

**Comment by Mjimenez01** [comment]
Ok, thanks for your help jberezanski, I really appreciate it. Do you recommend that I  create a ticket with Microsoft to get visibility on this?

**Comment by jberezanski** [comment]
Yes, I believe reporting it to Microsoft would be the best thing to do to get it fixed. I'm not sure what the best feedback channel would be in this case (given that VS 2015 is a rather old product, already out of mainstream support), but https://developercommunity.visualstudio.com/ might be a good start.

**Comment by jberezanski** [comment]
In https://developercommunity.visualstudio.com/t/installation-of-visual-studio-2015-web-installer-f/1412594 Microsoft confirmed that the removal of installation files was deliberate and they no longer support installing VS 2015 via the web installer.
