### ISSUE TITLE
Updating visualstudio2019buildtools 

### ISSUE THREAD

**Issue by JikaGrawe** [jberezanski/ChocolateyPackages#106]
@jberezanski im installing choco packages via puppet and im not able to find out why puppet unable to update visualstudio2019buildtools from version 16.8.6.0 to the version 16.9.5.0 

choco install visualstudio2019buildtools --package-parameters " --add Microsoft.VisualStudio.Component.VC.Tools.x86.x64 --add Microsoft.VisualStudio.Component.Windows10SDK.19041 --includeRecommended --passive --includeOptional "
 

ERROR: Running ["C:\WINDOWS\TEMP\chocolatey\visualstudio2019buildtools\16.9.5.0\vs_BuildTools.exe" update --passive --includeRecommended --wait --installPath "C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools" --norestart --add Microsoft.VisualStudio.Component.VC.Tools.x86.x64 --add Microsoft.VisualStudio.Component.Windows10SDK.18362 --includeOptional] was not successful. Exit code was '87'. 

See log for possible error messages.
The upgrade of visualstudio2019buildtools was NOT successful.
Error while running 'C:\ProgramData\chocolatey\lib\visualstudio2019buildtools\tools\ChocolateyInstall.ps1'.

Failures
- visualstudio2019buildtools (exited 87) - Error while running 'C:\ProgramData\chocolatey\lib\visualstudio2019buildtools\tools\ChocolateyInstall.ps1'.
See log for details. (corrective)

**Comment by jberezanski** [comment]
The Visual Studio Installer does not support `--add ...` parameters during update.

**Comment by jberezanski** [comment]
See also #93.
