### ISSUE TITLE
Latest update 16.10.0 fails to install

### ISSUE THREAD

**Issue by j-w-jones** [jberezanski/ChocolateyPackages#107]
The previous version 16.9.5 worked fine but when I try now (with the latest version) it fails. I'm using:

choco install -y --execution-timeout=10000 visualstudio2019community --package-parameters "--add Microsoft.VisualStudio.Workload.NativeDesktop --includeRecommended --includeOptional --passive"

This is on a brand new Windows 10 VM so no previous installs of VS are present.

**Comment by jberezanski** [comment]
Please provide these log files:
```
%ChocolateyInstall%\Logs\chocolatey.log
%TEMP%\chocolatey\dd_*.log
```

Also: please run these commands in the VM in PowerShell with administrative rights and provide the result:

```
Get-ItemProperty -Path 'HKLM:\Software\Microsoft\Windows NT\CurrentVersion' -Name BuildLabEx,DisplayVersion,CurrentBuild,ProductName
Get-HotFix | Format-Table -AutoSize
```

(for the record, the package installs correctly on my test machine - Windows 10 Pro 2004, fully patched on 2020-12-19)

**Comment by j-w-jones** [comment]
The output from the two commands are here. I have also attached a zip file of the log files.

PS C:\WINDOWS\system32> Get-ItemProperty -Path 'HKLM:\Software\Microsoft\Windows NT\CurrentVersion' -Name BuildLabEx,DisplayVersion,CurrentBuild,ProductName


BuildLabEx     : 19041.1.amd64fre.vb_release.191206-1406
DisplayVersion : 20H2
CurrentBuild   : 19042
ProductName    : Windows 10 Enterprise
PSPath         : Microsoft.PowerShell.Core\Registry::HKEY_LOCAL_MACHINE\Software\Microsoft\Windows NT\CurrentVersion
PSParentPath   : Microsoft.PowerShell.Core\Registry::HKEY_LOCAL_MACHINE\Software\Microsoft\Windows NT
PSChildName    : CurrentVersion
PSDrive        : HKLM
PSProvider     : Microsoft.PowerShell.Core\Registry



PS C:\WINDOWS\system32> Get-HotFix | Format-Table -AutoSize

Source          Description     HotFixID  InstalledBy         InstalledOn
------          -----------     --------  -----------         -----------
DESKTOP-EGDGUSF Update          KB5003254 NT AUTHORITY\SYSTEM 09/06/2021 00:00:00
DESKTOP-EGDGUSF Update          KB4562830 NT AUTHORITY\SYSTEM 14/05/2021 00:00:00
DESKTOP-EGDGUSF Security Update KB4570334                     18/11/2020 00:00:00
DESKTOP-EGDGUSF Update          KB4577586 NT AUTHORITY\SYSTEM 14/05/2021 00:00:00
DESKTOP-EGDGUSF Security Update KB4580325                     19/11/2020 00:00:00
DESKTOP-EGDGUSF Security Update KB4586864                     19/11/2020 00:00:00
DESKTOP-EGDGUSF Security Update KB5003637 NT AUTHORITY\SYSTEM 09/06/2021 00:00:00
DESKTOP-EGDGUSF Update          KB5003503 NT AUTHORITY\SYSTEM 09/06/2021 00:00:00

[Chocolatey Logs.zip](https://github.com/jberezanski/ChocolateyPackages/files/6623527/Chocolatey.Logs.zip)

**Comment by jberezanski** [comment]
Thank you!

dd_setup_20210609115726_errors.log shows this:

```
Package 'Win10SDK_10.0.19041,version=10.0.19041.1' failed to download from 'https://download.visualstudio.microsoft.com/download/pr/5eeaf3c7-015f-442c-8d63-aea17e5e6aef/6ec381fa716a2ed419c2141cc09606ee/a1e2a83aa8a71c48c742eeaff6e71928.cab'.
    Search URL
        https://aka.ms/VSSetupErrorReports?q=PackageId=Win10SDK_10.0.19041;PackageAction=DownloadPackage;ReturnCode=0x80096004
    Details
        WebClient download failed: SHA256 verification for 'a1e2a83aa8a71c48c742eeaff6e71928.cab' failed. Expected hash: 4F1B720286118CB2BFAB2119C29873F2BA96691D213529FFE53BFD3904813177, Actual hash: 375A80A5B5DBB2F6BACD170636A97AAAADE93C06DB2919452218F0A696FF87A3
        Bits download failed: SHA256 verification for 'a1e2a83aa8a71c48c742eeaff6e71928.cab' failed. Expected hash: 4F1B720286118CB2BFAB2119C29873F2BA96691D213529FFE53BFD3904813177, Actual hash: 375A80A5B5DBB2F6BACD170636A97AAAADE93C06DB2919452218F0A696FF87A3
        WinInet download failed: SHA256 verification for 'a1e2a83aa8a71c48c742eeaff6e71928.cab' failed. Expected hash: 4F1B720286118CB2BFAB2119C29873F2BA96691D213529FFE53BFD3904813177, Actual hash: 375A80A5B5DBB2F6BACD170636A97AAAADE93C06DB2919452218F0A696FF87A3
    Impacted workloads
        Desktop development with C++ (Microsoft.VisualStudio.Workload.NativeDesktop,version=16.10.31205.180)
    Impacted components
        Windows 10 SDK (10.0.19041.0) (Microsoft.VisualStudio.Component.Windows10SDK.19041,version=16.10.31205.252)
```

I have reproduced this on my test machine. (The difference in my earlier test was that I installed the core package only, without adding any workloads.)

Anyway, it seems to be a bug in the Visual Studio installer (specifically, the checksum of the Win10SDK component is probably incorrect in the VS component manifest file, which drives the install process). I expect Microsoft will fix this soon.

**Comment by j-w-jones** [comment]
Ok. Thanks for looking into it.

Get Outlook for Android<https://aka.ms/AAb9ysg>

________________________________

**Comment by jberezanski** [comment]
part of the manifest:
```
                                          {
                                              "fileName":  "Installers\\a1e2a83aa8a71c48c742eeaff6e71928.cab",
                                              "sha256":  "4F1B720286118CB2BFAB2119C29873F2BA96691D213529FFE53BFD3904813177",
                                              "size":  22849294,
                                              "url":  "https://download.visualstudio.microsoft.com/download/pr/5eeaf3c7-015f-442c-8d63-aea17e5e6aef/6ec381fa716a2ed419c2141cc09606ee/a1e2a83aa8a71c48c742eeaff6e71928.cab",
```

When I download that file, the sha256 hash is 375A80A5B5DBB2F6BACD170636A97AAAADE93C06DB2919452218F0A696FF87A3, same as shown in the log from your machine.

**Comment by jberezanski** [comment]
What's funny is that inside the downloaded .cab file is just this text: `DS Download API`.
Seems like a bug/misconfiguration on the backend or invalid url.

**Comment by j-w-jones** [comment]
I wonder if the Fastly outage yesterday had anything to do with it.

Get Outlook for Android<https://aka.ms/AAb9ysg>

________________________________

**Comment by jberezanski** [comment]
I thought Microsoft used Akamai as CDN, but who knows really.

VS 16.10.1 has just been released and seems to fix the problem. I've published the updated packages on chocolatey.org.

**Comment by j-w-jones** [comment]
They might do - I don't know. It just seemed a coincidence.

I have tried it this morning and everything is working fine.

Thanks for your help,

Jason
