### ISSUE TITLE
Issues with pulling installer from Microsoft server

### ISSUE THREAD

**Issue by brokulante** [jberezanski/ChocolateyPackages#112]
Hi,
I am trying to install `visualstudio2019buildtools` package via chocolatey without success. Reason for it seems to be Microsoft servers that respond with 404 HTTP Error code while trying to download dependencies (check the output of `choco install` command below)

```Chocolatey v0.10.15
Installing the following packages:
visualstudio2019buildtools
By installing you accept licenses for the packages.

dotnetfx v4.8.0.20190930 [Approved]
dotnetfx package files install completed. Performing other installation steps.
Downloading dotnetfx 64 bit
  from 'https://download.visualstudio.microsoft.com/download/pr/014120d7-d689-4305-befd-3cb711108212/0fd66638cde16859462a6243a4629a50/ndp48-x86-x64-allos-enu.exe'

Download of ndp48-x86-x64-allos-enu.exe (111.94 MB) completed.
Hashes match.
Installing dotnetfx...
WARNING: Microsoft .NET Framework 4.8 has been installed, but a reboot is required to finalize the installation. Until the computer is rebooted, dependent packages may fail to install or function properly.
 The install of dotnetfx was successful.
  Software installed as 'exe', install location is likely default.

visualstudio2019buildtools v16.10.4.0 [Approved]
visualstudio2019buildtools package files install completed. Performing other installation steps.
Attempt to get headers for https://aka.ms/vs/16/release/channel failed.
  The remote file either doesn't exist, is unauthorized, or is forbidden for url 'https://aka.ms/vs/16/release/channel'. Exception calling "GetResponse" with "0" argument(s): "The remote server returned an error: (404) Not Found."
Downloading channel manifest
  from 'https://aka.ms/vs/16/release/channel'
ERROR: The remote file either doesn't exist, is unauthorized, or is forbidden for url 'https://aka.ms/vs/16/release/channel'. Exception calling "GetResponse" with "0" argument(s): "The remote server returned an error: (404) Not Found."
The install of visualstudio2019buildtools was NOT successful.
Error while running 'C:\ProgramData\chocolatey\lib\visualstudio2019buildtools\tools\ChocolateyInstall.ps1'.
 See log for details.

Chocolatey installed 1/2 packages. 1 packages failed.
 See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).

Packages requiring reboot:
 - dotnetfx (exit code 3010)

The recent package changes indicate a reboot is necessary.
 Please reboot at your earliest convenience.

Failures
 - visualstudio2019buildtools (exited 404) - Error while running 'C:\ProgramData\chocolatey\lib\visualstudio2019buildtools\tools\ChocolateyInstall.ps1'.
 See log for details.
 ```
 
 Is there anything that can be done from maintainers end, or is this problem on Microsoft end?

**Comment by thumbard** [comment]
I'm getting a similar error with _**choco install vcredist-all -y**_ on an AWS ec2 instance while building with Packer. 

amazon-ebs.mep_ami: vcredist140 v14.29.30040 [Approved]
    amazon-ebs.mep_ami: vcredist140 package files install completed. Performing other installation steps.
    amazon-ebs.mep_ami: Attempt to get headers for https://download.visualstudio.microsoft.com/download/pr/888b4c07-c602-499a-9efb-411188496ce7/F3A86393234099BEDD558FD35AB538A6E4D9D4F99AD5ADFA13F603D4FF8A42DC/VC_redist.x86.exe failed.
    amazon-ebs.mep_ami:   The remote file either doesn't exist, is unauthorized, or is forbidden for url 'https://download.visualstudio.microsoft.com/download/pr/888b4c07-c602-499a-9efb-411188496ce7/F3A86393234099BEDD558FD35AB538A6E4D9D4F99AD5ADFA13F603D4FF8A42DC/VC_redist.x86.exe'. Exception calling "GetResponse" with "0" argument(s): "The remote server returned an error: (404) Not Found."
    amazon-ebs.mep_ami: Downloading vcredist140-x86
    amazon-ebs.mep_ami:   from 'https://download.visualstudio.microsoft.com/download/pr/888b4c07-c602-499a-9efb-411188496ce7/F3A86393234099BEDD558FD35AB538A6E4D9D4F99AD5ADFA13F603D4FF8A42DC/VC_redist.x86.exe'
    amazon-ebs.mep_ami: ERROR: The remote file either doesn't exist, is unauthorized, or is forbidden for url 'https://download.visualstudio.microsoft.com/download/pr/888b4c07-c602-499a-9efb-411188496ce7/F3A86393234099BEDD558FD35AB538A6E4D9D4F99AD5ADFA13F603D4FF8A42DC/VC_redist.x86.exe'. Exception calling "GetResponse" with "0" argument(s): "The remote server returned an error: (404) Not Found."
    amazon-ebs.mep_ami: The install of vcredist140 was NOT successful.
    amazon-ebs.mep_ami: Error while running 'C:\ProgramData\chocolatey\lib\vcredist140\tools\chocolateyInstall.ps1'.
    amazon-ebs.mep_ami:  See log for details.

**Comment by aaronrl95** [comment]
Likewise when trying running the following command - `choco install visualstudio2019buildtools`. Results in the following error: 
`amazon-ebs: Downloading channel manifest[0m
[0;32m    amazon-ebs:   from 'https://aka.ms/vs/16/release/channel'[0m
[0;32m    amazon-ebs:[0m
[0;32m    amazon-ebs: Progress: 99% - Saving 128 KB of 129.08 KB[0m
[0;32m    amazon-ebs: Progress: 100% - Completed download of C:\Users\Administrator\AppData\Local\Temp\chocolatey\chocolatey-visualstudio.extension\ChannelManifest_-602808024.man (129.08 KB).[0m
[0;32m    amazon-ebs: Download of ChannelManifest_-602808024.man (129.08 KB) completed.[0m
[0;32m    amazon-ebs: Downloading catalog manifest[0m
[0;32m    amazon-ebs:   from 'https://download.visualstudio.microsoft.com/download/pr/acfc792d-506b-4868-9924-aeedc61ae654/5165d2c72e51038a0e0069b2f170ab7ef7ae4a4b4cb5b84677876c2a9e9e74b2/VisualStudio.vsman'[0m
[0;32m    amazon-ebs: ERROR: The remote file either doesn't exist, is unauthorized, or is forbidden for url 'https://download.visualstudio.microsoft.com/download/pr/acfc792d-506b-4868-9924-aeedc61ae654/5165d2c72e51038a0e0069b2f170ab7ef7ae4a4b4cb5b84677876c2a9e9e74b2/VisualStudio.vsman'. Exception calling "GetResponse" with "0" argument(s): "The remote server returned an error: (404) Not Found."[0m
[0;32m    amazon-ebs: The install of visualstudio2019buildtools was NOT successful.[0m
[0;32m    amazon-ebs: Error while running 'C:\ProgramData\chocolatey\lib\visualstudio2019buildtools\tools\ChocolateyInstall.ps1'.[0m
[0;32m    amazon-ebs:  See log for details.[0m
[0;32m    amazon-ebs:[0m
[0;32m    amazon-ebs: Chocolatey installed 3/4 packages. 1 packages failed.[0m
[0;32m    amazon-ebs:  See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).[0m
[0;32m    amazon-ebs:[0m
[0;32m    amazon-ebs: Failures[0m
[0;32m    amazon-ebs:  - visualstudio2019buildtools (exited 404) - Error while running 'C:\ProgramData\chocolatey\lib\visualstudio2019buildtools\tools\ChocolateyInstall.ps1'.[0m
[0;32m    amazon-ebs:  See log for details.[0m`

Attemtping the command with previous versions results in the same error.

**Comment by fbaptista** [comment]
Same here, will update once we get the fix / WA

**Comment by jberezanski** [comment]
It looks like a major malfunction/misconfiguration on Microsoft servers. Even the VS installer download links from https://visualstudio.microsoft.com/downloads/ fail with 404 Not Found.

**Comment by jberezanski** [comment]
I believe the problem is resolved - the VS manifest urls work from my machine, at least.
