### ISSUE TITLE
Thank you for the very detailed description.

### ISSUE THREAD

**Issue by khashayarnazari** [jberezanski/ChocolateyPackages#113]
Thank you for the very detailed description.

Please be aware that there have been issues with the Windows 10 SDK component recently, caused by errors on Microsoft side (https://github.com/jberezanski/ChocolateyPackages/issues/107). The symptoms were different than in your case (the component simply failed to install with a clear error message), but still, you can try again now that the issue has been fixed.

Assuming your problem does not go away, I'd like to ask you to provide the (numerous) log files generated by the Visual Studio Installer: `$Env:TEMP\chocolatey\dd_*.log`. They usually are enough to identify any problems with the VS install itself.

The fact that the Chocolatey log just stops is curious indeed and yes, it may indicate that choco.exe is being killed by something. Now, I'm not familiar with Packer, but perhaps by correlating the VS installer logs with the Packer log it might be possible to determine whether the VS installer continues running in the background.

> choco install visualstudio2019buildtools && choco install visualstudio2019-workload-vctools

I noticed you do not pass `-y` to choco.exe, which is normally required on a default install. I assume you are enabling the `allowGlobalConfirmation` feature - is that correct? What other Chocolatey settings do you change from the default values?

> I wonder if there is a timeout

Yes, there is:
```
     --timeout, --execution-timeout=VALUE
     CommandExecutionTimeout (in seconds) - The time to allow a command to
       finish before timing out. Overrides the default execution timeout in the
       configuration of 2700 seconds. '0' for infinite starting in 0.10.4.
```
I believe, however, that choco.exe would write a clear message if the timeout was reached (but I'm not 100% sure about it). You can try with some large value, such as `--execution-timeout 108000` (it's what I use on slow virtual machines when testing the VS packages).

_Originally posted by @jberezanski in https://github.com/jberezanski/ChocolateyPackages/issues/108#issuecomment-860192381_

**Comment by jberezanski** [comment]
What is the purpose of this issue? The description is just a copy+paste from my post.
