### ISSUE TITLE
netfx-4.7.1-devpack fails to install since last week

### ISSUE THREAD

**Issue by felfert** [jberezanski/ChocolateyPackages#114]
Apparently, Microsoft has removed this download last week. Unfortunately, this also appears to be a dependency of visualstudio2017-workload-universalbuildtools. Any chance to fix this?

**Comment by felfert** [comment]
Tried to download it directly and it appears, that the offline installer is still available at
https://download.visualstudio.microsoft.com/download/pr/e5eb8d37-5bbd-4fb7-a71d-b749e010ef9f/601437d729667ecd29020a829fbc4881/ndp471-devpack-enu.exe

**Comment by jberezanski** [comment]
Yeah, I just fixed a similar issue with 4.7.2. Apparently Microsoft decided to change download links en masse.
Thanks for reporting, I should be able to fix that soon.

**Comment by jberezanski** [comment]
Updated and published: 4.6.2, 4.7, 4.7.1.

**Comment by felfert** [comment]
Should this be updated as well?
https://github.com/jberezanski/ChocolateyPackages/blob/9df427d9927d7dc045241bce40f638de7d9f1c41/visualstudio2017-workload-universalbuildtools/visualstudio2017-workload-universalbuildtools.nuspec#L61

**Comment by jberezanski** [comment]
No, this specifies only the minimum version of the dependency. Choco will automatically select the highest netfx-4.7.1-devpack package version if the package is not installed yet.

**Comment by jberezanski** [comment]
Note that the updated netfx-4.7.1-devpack version must still pass moderation until it becomes "visible".

**Comment by jberezanski** [comment]
The updated netfx-4.7.1-devpack has been approved. @felfert can you confirm that your issue is resolved?

**Comment by felfert** [comment]
Yes, I can confirm that everything works again.
Installed  visualstudio2017-workload-universalbuildtools on a pristine VM and it correctly pulled and installed netfx-4.7.1-devpack:
````
netfx-4.7.1-devpack v4.7.2558.20210905 [Approved]
netfx-4.7.1-devpack package files install completed. Performing other installation steps.
Downloading netfx-4.7.1-devpack 64 bit
  from 'https://download.visualstudio.microsoft.com/download/pr/e5eb8d37-5bbd-4fb7-a71d-b749e010ef9f/601437d729667ecd29020a829fbc4881/ndp471-devpack-enu.exe'

Download of ndp471-devpack-enu.exe (89.95 MB) completed.
Hashes match.
Installing netfx-4.7.1-devpack...
netfx-4.7.1-devpack has been installed.
  netfx-4.7.1-devpack may be able to be automatically uninstalled.
 The install of netfx-4.7.1-devpack was successful.
  Software installed as 'exe', install location is likely default.
````

**Comment by felfert** [comment]
... and many thanks for the fast response and fix :-)
