### ISSUE TITLE
dotnetfx v4.7.2.20180712 installation fails

### ISSUE THREAD

**Issue by tempora-mutantur** [jberezanski/ChocolateyPackages#115]
Hi.

The dotnetfx v4.7.2.20180712 version cannot be installed

_The remote file either doesn't exist, is unauthorized, or is forbidden for url 'https://download.microsoft.com/download/6/E/4/6E48E8AB-DC00-419E-9704-06DD46E5F81D/NDP472-KB4054530-x86-x64-AllOS-ENU.exe'. Exception calling "GetResponse" with "0" argument(s): "The remote server returned an error: (404) Not Found."_

Could you please tell if this is going to be resolved or some other package should be used for this purpose?
Thank you

**Comment by jberezanski** [comment]
For the record, dotnetfx version 4.7.2.20210909 with updated url and checksum was published today.
