### ISSUE TITLE
Make Get-WillowInstalledProducts public

### ISSUE THREAD

**Issue by flcdrg** [jberezanski/ChocolateyPackages#12]
I'd like to use Get-WillowInstalledProducts from chocolatey-visualstudio.extension to check if VS2017 is installed as a dependency of a package for installing a VS2017 extension.

It would be great if Get-WillowInstalledProducts was exported publicly so I could use it more easily.

**Comment by jberezanski** [comment]
That function is really a short-term hack; it relies on undocumented VS internals, which may change with any VS update. I am currently [working](https://github.com/Microsoft/vssetup.powershell/pull/19) on making the official [VSSetup](https://blogs.msdn.microsoft.com/heaths/2017/01/25/visual-studio-setup-powershell-module-available/) PowerShell module usable by Chocolatey. Once that PR is accepted, I'll probably remove that function or reimplement it as a thin wrapper over `Get-VSSetupInstance`.

Until then, you could use the [vswhere.exe](https://blogs.msdn.microsoft.com/heaths/2017/02/25/vswhere-available/) tool (which is already [available on chocolatey.org](https://chocolatey.org/packages/vswhere)).

(Besides, if that function was to be made public, it would definitely need a better name...)

**Comment by jberezanski** [comment]
On second thought, I _do_ see the value in having this function available from `chocolatey-visualstudio.extension`, regardless of its implementation (in fact, hiding the technical details is part of the value). Any ideas for a nice, official name (Get-VisualStudio...)?

**Comment by flcdrg** [comment]
`Get-VisualStudio` seams reasonable

**Comment by jberezanski** [comment]
I was thinking about a more descriptive/precise name, something that would convey the meaning of the current one ("gets all instances of Visual Studio products installed using the VS 2017 (or later) 'Willow' installer") but start with "VisualStudio" as other public functions of this extension do.

(Yes, naming is hard 😉)

`Get-VisualStudioInstance`? It could be enhanced to return basic info about VS 2015 and earlier, like `vswhere.exe` does.

**Comment by flcdrg** [comment]
That's good too :-)

**Comment by jberezanski** [comment]
Here's the proposed shape of objects returned by the new public function. It will return PSObjects with properties:

`InstallationPath` - the path of the instance, e.g. C:\Program Files (x86)\Microsoft Visual Studio\2017\Community
`InstallationVersion` - a System.Version object, e.g. 15.0.26228.9
`ProductId` - e.g. Microsoft.VisualStudio.Product.Community
`ChannelId` - e.g. VisualStudio.15.Release

(the two latter properties will be empty for instances of Visual Studio 2015 and earlier)

I chose a minimal set of properties easily obtainable either using the VSSetup PS module or from vswhere.exe (I don't know whether I will be able to use the PS module). Will this be enough for your use case?

**Comment by flcdrg** [comment]
That's more than enough for me. My case is just to test if 2017 is installed or not

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by jberezanski** [comment]
@flcdrg here's something for you to test:

https://www.myget.org/feed/jberezanski-chocolateypackages-dev/package/nuget/chocolatey-visualstudio.extension/1.3.0
https://github.com/jberezanski/ChocolateyPackages/tree/visualstudio2017enterprise

````
PS C:\> cup -y chocolatey-visualstudio.extension --source https://www.myget.org/F/jberezanski-chocolateypackages-dev/api/v2
(...)
PS C:\> ipmo C:\ProgramData\Chocolatey\extensions\chocolatey-visualstudio\chocolatey-visualstudio.extension.psm1
PS C:\> Get-VisualStudioInstance | fl


ProductId           : Microsoft.VisualStudio.Product.Community
InstallationPath    : C:\Program Files (x86)\Microsoft Visual Studio\2017\Community
ChannelId           : VisualStudio.15.Release
InstallationVersion : 15.0.26403.0

ProductId           : Microsoft.VisualStudio.Product.Enterprise
InstallationPath    : C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise
ChannelId           : VisualStudio.15.Release
InstallationVersion : 15.0.26403.0

ProductId           : Microsoft.VisualStudio.Product.TeamExplorer
InstallationPath    : C:\Program Files (x86)\Microsoft Visual Studio\2017\TeamExplorer
ChannelId           : VisualStudio.15.Release
InstallationVersion : 15.0.26403.0

ProductId           :
InstallationPath    : C:\Program Files (x86)\Microsoft Visual Studio 14.0\
ChannelId           :
InstallationVersion : 14.0
````

**Comment by flcdrg** [comment]
yeah, that looks nice. Works on mine too.

**Comment by jberezanski** [comment]
Great, I'll release it in a few hours.

**Comment by jberezanski** [comment]
https://chocolatey.org/packages/chocolatey-visualstudio.extension/1.3.0

**Comment by jberezanski** [comment]
@flcdrg I'm assuming the released version works for you - can we close this issue now?

**Comment by flcdrg** [comment]
Yes, thanks

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
