### ISSUE TITLE
visualstudio2022-workload-netcorebuildtools is missing

### ISSUE THREAD

**Issue by kwaazaar** [jberezanski/ChocolateyPackages#125]
I see a package called [visualstudio2019-workload-netcorebuildtools](https://community.chocolatey.org/packages/visualstudio2019-workload-netcorebuildtools), but no equivalent for 2022. Is that intentionally?

**Comment by OraDotNetDev** [comment]
> I see a package called [visualstudio2019-workload-netcorebuildtools](https://community.chocolatey.org/packages/visualstudio2019-workload-netcorebuildtools), but no equivalent for 2022. Is that intentionally?

I think so as the NetCoreBuildTools Workload been dropped from the [Visual Studio 2022 workloads](https://docs.microsoft.com/en-us/visualstudio/install/workload-component-id-vs-build-tools?view=vs-2022).

The [NetCoreTools](https://docs.microsoft.com/en-us/visualstudio/install/workload-component-id-vs-professional?view=vs-2022) workload has also been dropped, at least for my requirements the NetWeb workload with the optional flag alongside the the Azure Workload with recommended replace it.

**Comment by jberezanski** [comment]
Yes, there is no such workload for VS 2022 and the one for 2019 has been deprecated by MS, too.
