### ISSUE TITLE
[visualstudio2019buildtools] Error due to file access rights deleting `.lastupdatedate`

### ISSUE THREAD

**Issue by SeanKilleen** [jberezanski/ChocolateyPackages#127]
Versions:

* Current package version: v16.11.11.0 installed. 
* Target package version: 16.11.13.0
* OS Version: Windows 10 Version 21H1 (OS Build 19043.1645)

I tried:

* ✅ Running as admin
* ✅ Tried with powershell core and powershell for windows 

Output:

```
Progress: Downloading visualstudio2019buildtools 16.11.13.0... 100%

visualstudio2019buildtools v16.11.13.0 [Approved]
visualstudio2019buildtools package files upgrade completed. Performing other installation steps.
ERROR: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Cannot remove item C:\Users\SeanK\AppData\Local\Microsoft\VisualStudio\Packages\_Channels\c291ba1b\.lastupdatedate: You do not have sufficient access rights to perform this operation.
The upgrade of visualstudio2019buildtools was NOT successful.
Error while running 'C:\ProgramData\chocolatey\lib\visualstudio2019buildtools\tools\ChocolateyInstall.ps1'.
 See log for details.
```

I'm using Windows Defender, so I added an exemption for `C:\Users\SeanK\AppData\Local\Microsoft\VisualStudio\Packages\_Channels` and disabled/re-enabled scanning. The same issue persisted. So I don't think it's an AV issue in this case.

**Comment by jberezanski** [comment]
I've seen it once, I think, out of several tens of installs, so it may be hard to reproduce. But I have an idea for a mitigation and I might implement something over the weekend.

**Comment by OraDotNetDev** [comment]
Just had this occur on a couple of machines whilst upgrading the visualstudio2022professional v 117.1.6.0 package would worth uploading any logs?

**Comment by jberezanski** [comment]
@OraDotNetDev  Yes, please try after upgrading the extension. The newest VS 2022 packages already depend on it, but they are still in moderation.

**Comment by jberezanski** [comment]
The root cause is that the latest versions of Visual Studio Installer started producing files with the "Hidden" attribute set, which Remove-Item refuses to delete without -Force.

**Comment by OraDotNetDev** [comment]
Hi Jakub, thanks very much for your speedy response on this 🥇 

I've tested this with the latest chocolatey-visualstudio.extension release (1.10.2) https://github.com/jberezanski/ChocolateyPackages/blob/master/chocolatey-visualstudio.extension/CHANGELOG.md#version-1102 and this resolves the issue.

**Comment by jberezanski** [comment]
Glad to hear it!

Meanwhile, the updated VS 2022 packages have encountered issues in moderation - apparently, the VS 2022 Installer has started using operating system functionality not available on Server 2012 R2 (the OS the Chocolatey Package Verifier is currently based on) and the packages now fail to install on 2012 R2, so they fail the verification step of moderation. (To be fair, the official system requirements of VS 2022 do say that only Server 2016+ is supported, but it worked on older OS until now.) I need to ask for moderation exemptions, so there may be a delay.

**Comment by jberezanski** [comment]
All packages have passed moderation now.
