### ISSUE TITLE
Visual Studio 2022 Remote Tools Support

### ISSUE THREAD

**Issue by Nirvana-Y** [jberezanski/ChocolateyPackages#132]
Hi, 

Do we have plan to support Visual Studio 2022 Remote Tools?

I can help add one if you provide some contribution instructions.

**Comment by jberezanski** [comment]
I haven't personally had the need to use the 2022 Remote Tools yet, but yes, it would probably be useful.
If you would like to help, I think the quickest way would be to copy the existing 2019 package under a new name and update data.ps1 and the nuspec file. (I expect the install/uninstall scripts could remain the same, they are driven by info from data.ps1.) Then you can open a PR and we'll smooth out any rough edges.
