### ISSUE TITLE
visualstudio2022buildtools not installing linker

### ISSUE THREAD

**Issue by barlog-m** [jberezanski/ChocolateyPackages#147]
`choco install -y visualstudio2022buildtools`

run "Developer Command Prompt for VS 2022" app from start menu

```
**********************************************************************
** Visual Studio 2022 Developer Command Prompt v17.6.4
** Copyright (c) 2022 Microsoft Corporation
**********************************************************************

C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools>link.exe
'link.exe' is not recognized as an internal or external command,
operable program or batch file.

C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools>ver
Microsoft Windows [Version 10.0.22621.1848]
```

Could you please tell me what am i doing wrong?

**Comment by jberezanski** [comment]
The `visualstudio2022buildtools` package by default only installs the minimal Build Tools, without any additional [components/workloads](https://learn.microsoft.com/en-us/visualstudio/install/workload-component-id-vs-build-tools?view=vs-2022) (just like the interactive installer does if you do not select anything). I'm guessing link.exe is part of the C++ tools, so you probably need the [Desktop development with C++](https://learn.microsoft.com/en-us/visualstudio/install/workload-component-id-vs-build-tools?view=vs-2022#desktop-development-with-c) workload. You can easily install that workload via Chocolatey using the `visualstudio2022-workload-vctools` package.
