### ISSUE TITLE
Unable to pass multiple --add package parameters

### ISSUE THREAD

**Issue by maxaf** [jberezanski/ChocolateyPackages#16]
For example:

```
PS C:\Users\Administrator> choco install --verbose --force -y visualstudio2017community --execution-timeout=0 --package-parameters "--passive --locale en-US --add Microsoft.Component.MSBuild --add Microsoft.VisualStudio.Component.TestTools.Core --add Microsoft.VisualStudio.Workload.ManagedDesktop"
```
Throws the following:
```
ERROR: Exception calling "Add" with "2" argument(s): "Item has already been added. Key in dictionary: 'add'  Key being added: 'add'"
```
Behold also the [full `chocolatey.log`](https://gist.githubusercontent.com/maxaf/186571cec159b1c06b2c53cf45f5e628/raw/cab8ca6791315ac3857be5a26229fb303d4d20b5/chocolatey.log).

**Comment by jberezanski** [comment]
Yes, this is currently a limitation of the way the extension processes package parameters. Will fix.

**Comment by variac** [comment]
Even adding one in e.g. desktop C++ workload doesn't seem to work. I just want to add 2015 build tools, and nothing happens, it just eats the command line parameter.

**Comment by dickymoore** [comment]
Is there a fix or a workaround for this yet?

**Comment by jberezanski** [comment]
No fix yet (pull requests welcome).

For adding workloads (with default settings), you may use the workload packages:

````
cinst -y visualstudio2017community --package-parameters "--passive --locale en-US"
cinst -y visualstudio2017-workload-manageddesktop --package-parameters "--passive --locale en-US"
````

For more fine-grained addition of individual components, you can invoke the Visual Studio installer directly:

````
& "${Env:ProgramFiles(x86)}\Microsoft Visual Studio\Installer\vs_installer.exe" modify `
--installPath "${Env:ProgramFiles(x86)}\Microsoft Visual Studio\2017\Community" `
--add Microsoft.Component.MSBuild `
--add Microsoft.VisualStudio.Component.TestTools.Core `
--passive
````

**Comment by adriangodong** [comment]
@jberezanski  I can pick this up if I have some sort of direction that you prefer. I guess the easiest way would be to use `List<KeyValuePair<string, string>>`?

I'm setting up a build machine that needs msbuild, .NET Core workload, and core test tools (and possibly even more).

**Comment by jberezanski** [comment]
Sure, all help is welcome!

I was thinking about leaving `[hashtable]` as the data structure used to store parsed package parameters, but using an array of strings instead of a single string as the value of a multivalued parameter. The parser (function `Parse-Parameters`) should only allow it for known multivalued parameters (add, remove, addProductLang, removeProductLang).

Next, each place where the package parameters hashtable gets converted into a flat string to be passed to the native installer would need to be modified to handle the multivalued parameters (at this point it would probably be a good idea to extract this logic into a function).

There is also at least one place where the extension uses the values of the `add` or `remove` parameters (in function `Start-VisualStudioModifyOperation`), but I believe the existing code is written so that it will work with an array without changes.

**Comment by jberezanski** [comment]
I needed to refactor argument string generation for unrelated purposes, so the extraction part mentioned above is done (`vsext-dev` branch). I might even have enough momentum to implement the multivalue parameter support myself in a couple of days, unless you beat me to it ;-)

**Comment by jberezanski** [comment]
OK, it's done in [extension version 1.6.0-rc7](https://chocolatey.org/packages/chocolatey-visualstudio.extension/1.6.0-rc7) available now on chocolatey.org. The supported multivalued parameters are: --add, --remove, --addProductLang, --removeProductLang.

Example command lines:
````
# update the extension to the prerelease version
cup chocolatey-visualstudio.extension --pre

# install VS 2017 Professional with two optional components and an additional language
cinst -y visualstudio2017professional --params "--add Microsoft.Net.Component.4.7.TargetingPack --add Microsoft.Net.Component.4.7.1.TargetingPack --locale en-US --addProductLang de-DE"

# add the Data workload and two additional components to all installed VS 2017 instances, skipping components recommended for that workload (they would be installed by default)
cinst -y visualstudio2017-workload-data --params "--add Microsoft.VisualStudio.Component.WebDeploy --add Microsoft.VisualStudio.Component.VisualStudioData --locale en-US --no-includeRecommended"
````

Please give it a try if you can. If nothing bad comes up, I'll release the extension as an official version in a couple of days.

**Comment by skajter** [comment]
I've tested on my VM and working fine :)

**Comment by jzinn** [comment]
I'm eagerly awaiting the official release.  Any ETA?

**Comment by jberezanski** [comment]
I've released [extension 1.6.0](https://chocolatey.org/packages/chocolatey-visualstudio.extension/1.6.0) with this fix today. I won't be releasing all VS 2017 product and workload packages just to update the dependency version, so when adding a workload to an existing installation please update the extension manually first: `cup chocolatey-visualstudio.extension`. (For new installations, Chocolatey will automatically install the latest available extension version regardless of the dependency version specified by the package.)

**Comment by jzinn** [comment]
It's working, thank you.

**Comment by kostasvl** [comment]
Hi @jberezanski. I'm trying the following command:

choco install visualstudio2017buildtools --params="--add Microsoft.VisualStudio.Workload.ManagedDesktopBuildTools --add Microsoft.Net.Component.4.7.2.TargetingPack --add Microsoft.Net.Component.4.7.2.SDK --add Microsoft.VisualStudio.Workload.MSBuildTools --add Microsoft.VisualStudio.Component.NuGet --add Microsoft.VisualStudio.Workload.VCTools --includeRecommended"

...and it seems the --add params are consumed by chocolatey:

Chocolatey v0.10.12-beta Business
Running in background mode
**Installing the following packages:
visualstudio2017buildtools;Microsoft.VisualStudio.Workload.ManagedDesktopBuildTools;Microsoft.Net.Component.4.7.2.TargetingPack;Microsoft.Net.Component.4.7.2.SDK;Microsoft.VisualStudio.Workload.MSBuildTools;Microsoft.VisualStudio.Component.NuGet;Microsoft.VisualStudio.Workload.VCTools**
...
Progress: Downloading visualstudio2017buildtools 15.9.11.0... 100%
....
 The install of visualstudio2017buildtools was successful.
...
**Microsoft.VisualStudio.Workload.ManagedDesktopBuildTools not installed. The package was not found with the source(s) listed.**
...
Chocolatey installed 1/7 packages. **6 packages failed.**
 See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).

I have chocolatey-visualstudio.extension 1.8.0.

Is this the same issue? Any ideas?

Thanks! :)
