### ISSUE TITLE
visualstudio.extension: Support offline layouts

### ISSUE THREAD

**Issue by pascalberger** [jberezanski/ChocolateyPackages#17]
It would be great if the visualstudio.extension could also be used to install [offline layouts](https://docs.microsoft.com/en-us/visualstudio/install/create-a-network-installation-of-visual-studio). Instead of passing a download URL in this case the link to the offline layout could be passed to the helper.

**Comment by jberezanski** [comment]
Yes, I've been thinking about it, too. I believe it should be quite easy to implement.

**Comment by jberezanski** [comment]
This is now supported in [extension version 1.5.0](https://github.com/jberezanski/ChocolateyPackages/blob/9dce011172982a92bfa9c1f306e1ef940eb13e14/chocolatey-visualstudio.extension/CHANGELOG.md), released today.

Example usage:

````
# Create the layout. VS will not be actually installed, the installation will "fail" with code 814.
cinst -y visualstudio2017professional --params "--layout D:\VS2017Prof"
# Install from the layout.
cinst -y visualstudio2017professional --params "--bootstrapperPath D:\VS2017Prof\vs_Professional.exe"
````

**Comment by jberezanski** [comment]
The feature has been available for a few months now, so I'll close the issue.
