### ISSUE TITLE
Bump to 15.3

### ISSUE THREAD

**Issue by skyguy94** [jberezanski/ChocolateyPackages#18]
15.3 bits dropped yesterday.

**Comment by jberezanski** [comment]
Soon :)

**Comment by skyguy94** [comment]
For next time, I'm willing to do a PR to help out, but do you have maintenance script for updating them somehow or do you do it by hand?

**Comment by jberezanski** [comment]
I have it automated partially: [a script](https://github.com/jberezanski/ChocolateyPackages/blob/master/tools/VS2017/runme.ps1) parses the VS download package, extracts download links, downloads the installer bootstrappers, invokes each of them to download an offline copy of installation packages (--layout), pulls the VS version numbers out of the downloaded channel manifest files and, finally, computes the hashes of the bootstrappers. The actual package update is currently still done by hand - I've been meaning to automate it as well, but did not have the time yet - been busy with implementing support for reliably updating an existing VS 2017 installation (not there yet, many problems to solve).

BUT, the way the packages are currently implemented, they actually do not need to be updated at all: the installer bootstrappers always install the latest version of VS (as noted in [package release notes](https://chocolatey.org/packages/VisualStudio2017Community/15.2.26430.20170605#releasenotes)).

See also: #10, #11.

**Comment by jberezanski** [comment]
Please see my response in the PR (#36).

**Comment by jberezanski** [comment]
The VS packages are getting regular updates now, so I'm closing this.
