### ISSUE TITLE
.NET 4.7.1 final

### ISSUE THREAD

**Issue by mbp** [jberezanski/ChocolateyPackages#21]
Would be great to see https://chocolatey.org/packages/dotnet4.7.1 being updated to final package. :-)

Thanks for doing this!

**Comment by rgl** [comment]
Isn't it already updated?

**Comment by mbp** [comment]
Not when I wrote the message, but yes it's there now. :-)

**Comment by jberezanski** [comment]
Ah, sorry, I forgot to close this :)
