### ISSUE TITLE
visualstudio2017: VS Installer upgrade might result in a corrupted VS Installer

### ISSUE THREAD

**Issue by jberezanski** [jberezanski/ChocolateyPackages#26]
When upgrading from an old version of the Visual Studio Installer (e.g. 1.4.30204.2 - an RC version), the VS Installer sometimes becomes corrupted, with some libraries missing. This results in errors such as:

````
---------------------------
vs_installershell.exe - System Error
---------------------------
The program can't start because ffmpeg.dll is missing from your computer. Try reinstalling the program to fix this problem. 
---------------------------
OK   
---------------------------
````

(also seen with node.dll)

An attempt to reinstall the VS installer (`vs_Setup.exe --quiet --update`) does not fix the issue:

````
ipmo C:\ProgramData\chocolatey\helpers\chocolateyInstaller.psm1
ipmo C:\ProgramData\chocolatey\lib\chocolatey-visualstudio.extension\extensions\chocolatey-visualstudio.extension.psm1
$p = start-process -PassThru -Wait -FilePath (Get-VisualStudioInstaller).Path -ArgumentList @('--help'); $p.ExitCode
# exit code: -1073741515 (missing ffmpeg.dll)
Install-VisualStudioInstaller -PackageName 'none' -Url 'https://download.visualstudio.microsoft.com/download/pr/100266713/68768867af8c4fd58753da539846fbad/vs_Setup.exe' -Checksum '0f29e6f95a8b0cc5d9d44abca233ef5eb9c103f3d80e5cc8d5edf34008807769' -ChecksumType 'SHA256' -RequiredVersion '1.12.111.1002' -Force
$p = start-process -PassThru -Wait -FilePath (Get-VisualStudioInstaller).Path -ArgumentList @('--help'); $p.ExitCode
# exit code: -1073741515 (missing ffmpeg.dll)
````

A working solution is to delete/rename the existing VS Installer directory:

````
(Get-VisualStudioInstaller).Path
gci (split-path (Get-VisualStudioInstaller).Path) # missing ffmpeg.dll
ren (split-path (Get-VisualStudioInstaller).Path) Installer.old
Install-VisualStudioInstaller -PackageName 'none' -Url 'https://download.visualstudio.microsoft.com/download/pr/100266713/68768867af8c4fd58753da539846fbad/vs_Setup.exe' -Checksum '0f29e6f95a8b0cc5d9d44abca233ef5eb9c103f3d80e5cc8d5edf34008807769' -ChecksumType 'SHA256'
gci (split-path (Get-VisualStudioInstaller).Path) # ffmpeg.dll present
$p = start-process -PassThru -Wait -FilePath (Get-VisualStudioInstaller).Path -ArgumentList @('--help'); $p.ExitCode
# exit code: 1 (ok, expected for --help)
````

Perhaps `Install-VisualStudioInstaller` could detect this situation and apply the above workaround automatically.

**Comment by jberezanski** [comment]
In more pathological cases, even `vs_installer.exe` and `vs_installershell.exe` themselves get removed.

The issue happens when the VS Installer is updated implicitly, as a prerequisite of a VS product install/update/modify operation. This is probably caused by the fact that the VS setup bootstrapper (vs_Setup.exe, vs_BuildTools.exe etc.) always invokes the existing (old) VS Installer, which then decides that it needs to update itself and does it imperfectly. Unless the bootstrapper behavior changes, the issue will persist.

A reliable workaround is to always explicitly update the VS Installer (`vs_Setup.exe --quiet --update`) before performing the main operation.

**Comment by jberezanski** [comment]
The extension package tries very hard to update and/or fix the installer, so this issue should not reappear.

**Comment by m-pollack** [comment]
I get an error message ever day since I updated a few days ago to VS 2019 16.3.6

![vsinstellershell](https://user-images.githubusercontent.com/49539220/67979255-1f1d4e00-fbd9-11e9-8b81-51b0529fb76c.JPG)
