### ISSUE TITLE
Installing VS 2017 via packer on Windows 2012 R2 "fails"

### ISSUE THREAD

**Issue by cosminonea** [jberezanski/ChocolateyPackages#34]
I am trying to install VS2017 on a Windows 2012 R2 in AWS via packer.
The code snippet of the provisioner looks like this:

```
{
      "type": "powershell",
      "inline": [
        "choco install visualstudio2017professional --package-parameters \"--allWorkloads --quiet --includeRecommended --includeOptional --locale en-US\""
      ]
}
```

The VS installer process starts and exits immediately but, apparently, with a 0 exit code. The same command works when I run it interactively by remoting into the machine.
Packer uses WinRM to connect and execute commands remotely.

I can't tell what is going on from the logs. Maybe I am missing some of the log files.
Could anyone here point me to the location of all the logs I need to check please?

**Comment by jberezanski** [comment]
The Chocolatey log is at $Env:ChocolateyInstall\Logs\chocolatey.log (typically C:\ProgramData\Chocolatey\Logs\chocolatey.log) and should contain much diagnostic info. The VS installer creates a lot of log files in $Env:TEMP\chocolatey (typically C:\Users\<username>\AppData\Local\Temp\chocolatey, but might be C:\Windows\Temp if choco is run under the SYSTEM identity, for example by PowerShell DSC) with names starting with "dd_".

The installation of VS involves installing several Windows updates and that does not work over WinRM due to the design of the Windows Update Agent API, which denies access to network logons - this might be the cause.

**Comment by cosminonea** [comment]
Yeah, I got that problem first but I solved the installation of the Windows updates required by installing them separately with an elevated account.

```
{
      "type": "powershell",
      "elevated_user": "admin",
      "elevated_password": "{{user `admin_password`}}",
      "inline": [
        "choco install chocolatey-visualstudio.extension",
        "choco install KB3033929",
        "choco install KB2919355",
        "choco install KB2999226",
        "choco install dotnet4.6.1"
     ]
}
```

I'll run it again and check all the logs...

**Comment by cosminonea** [comment]
Here are the logs: https://gist.github.com/cosminonea/99d5d3a133082e19794f45590f31ea43

I can't see any issues in the logs. The installation just stops.

**Comment by cosminonea** [comment]
I've been trying to understand it better by messing around with the steps in the packer config. It looks like a packer/WinRM problem. The packer task executed after a restart fails.

I changed my steps from this:

```
{
      "type": "powershell",
      "elevated_user": "admin",
      "elevated_password": "{{user `admin_password`}}",
      "inline": [
        "choco install chocolatey-visualstudio.extension",
        "choco install KB3033929",
        "choco install KB2919355",
        "choco install KB2999226",
        "choco install dotnet4.6.1",
        "choco install visualstudio2017-installer",
        "choco install sysinternals",
        "choco install fake --pre"
      ]
    },
    {
      "type": "windows-restart",
      "restart_timeout": "1h"
    },
    {
      "type": "powershell",
      "inline": [
        "choco install visualstudio2017professional --package-parameters \"--allWorkloads --quiet --includeRecommended --includeOptional --locale en-US\""
      ]
    }
```
To (notice the sleep in between): 
```
{
      "type": "powershell",
      "elevated_user": "admin",
      "elevated_password": "{{user `admin_password`}}",
      "inline": [
        "choco install chocolatey-visualstudio.extension",
        "choco install KB3033929",
        "choco install KB2919355",
        "choco install KB2999226",
        "choco install dotnet4.6.1",
        "choco install visualstudio2017-installer",
        "choco install sysinternals",
        "choco install fake --pre"
      ]
    },
    {
      "type": "windows-restart",
      "restart_timeout": "1h"
    },
    {
      "type": "powershell",
      "inline": [
        "echo 'Hack for packer!'",
        "Start-Sleep 120"
      ]
    },
    {
      "type": "powershell",
      "inline": [
        "choco install visualstudio2017professional --package-parameters \"--allWorkloads --quiet --includeRecommended --includeOptional --locale en-US\""
      ]
    }
```

I am not 100% sure what it is. It could be a bug in packer or after a restart, WinRM gets killed and restarted and packer loses connection.

Anyway, I'll close this as not related to the choco package.

**Comment by cosminonea** [comment]
I just found this in the logs, looks like WinRM is restarting for some reason:

```
The WinRM service is not listening for WS-Management requests. 

 User Action 
 If you did not intentionally stop the service, use the following command to see the WinRM configuration: 

 winrm enumerate winrm/config/listener
```

**Comment by jberezanski** [comment]
Glad you could find a workaround and thanks for sharing your diagnostic steps, they might help someone in the future.

Yes, it does not seem to be a package issue. I haven't seen such WinRM behavior before (I don't use packer, however). You might try logging process activity with [Process Monitor](https://malwaretips.com/threads/using-sysinternals-process-monitor-to-troubleshoot-problems-in-windows.45250/) to see whether something bad happens with the svchost process hosting the WinRM service.
