### ISSUE TITLE
DotNet 4.7.2 final has been released

### ISSUE THREAD

**Issue by Techcadia** [jberezanski/ChocolateyPackages#37]
As of 4/30/2018 it seems that 4.7.2 is now the current version of .NET

I see packages for netfx and dotnet 4.7.2 but they are preview only. Any chance we can get them update to the new code.

Thanks.

**Comment by jberezanski** [comment]
Thanks, I've been awaiting the release, yet I still missed it. I'll update the packages today or tomorrow (you can speed things up with a pull request).

**Comment by jberezanski** [comment]
https://chocolatey.org/packages/dotnetfx/4.7.2.0
https://chocolatey.org/packages/netfx-4.7.2-devpack
