### ISSUE TITLE
Install all security updates

### ISSUE THREAD

**Issue by Tacioandrade** [jberezanski/ChocolateyPackages#50]
Install all security updates

Good afternoon, I would like to hear from you if there is any way by using "Install-WindowsUpdate" to install all the security updates of a company without the need to pass KB by KB to client computers.

I work with Windows 7 clients in an environment without WSUS (our servers are all based on Linux or BSD) and I would like to use Chocolatey to update the client machines, the problem is that I have Windows 7 32Bits and 64Bits, at the same time that I have running Ubuntu Mate.

I would like to make use of Ansible + Chocolatey and Ansible + apt-get to update monthly my machine park, however pass KB by KB in my serial windows updates scripts rather complex, unlike Ubuntu where I can only pass an apt- get update && apt-get upgrade -y

Thank you in advance for your help.

**Comment by jberezanski** [comment]
The "Install-WindowsUpdate" function is designed only to install specific updates, downloaded as MSU files.
For detecting and installing all available updates you could use "Get-WUInstall" from the [PSWindowsUpdate module](https://gallery.technet.microsoft.com/scriptcenter/2d191bcd-3308-4edd-9de2-88dff796b0bc).

**Comment by Tacioandrade** [comment]
Perfect from there. I will start my tests today .... I liked the idea of using Chocolatey because it would automate everything with a tool only, the problem is the clients that do not have any security updates applied (newly formatted), for cases like this having to pass parameter by parameter all the more than 200 Windows updates to be deployed would be terrible.

**Comment by jberezanski** [comment]
You can create a Chocolatey package that calls Get-WUInstall. You could even publish it on chocolatey.org for the benefit of the community.
It seems a package for PSWindowsUpdate exists already (https://chocolatey.org/packages/PSWindowsUpdate), so your package can depend on it.
