### ISSUE TITLE
looking for a recipe to install c++ and python2.7

### ISSUE THREAD

**Issue by refack** [jberezanski/ChocolateyPackages#55]
Hello,

At the Node.js project we're trying to create an installer utility that will get all the build tools needed to later compile native addons.
ATM we use boxstarter to do:
```
choco upgrade -y python2
choco upgrade -y visualstudio2017buildtools
choco upgrade -y visualstudio2017-workload-vctools
```
But I was wondering if we could do it with a single package something like `visualstudio2017buildtools + vctools + python2`?

Any help would be much appreciated.

**Comment by jberezanski** [comment]
You can install all desired Visual Studio Build Tools components in one choco.exe invocation using package parameters, e.g.:

```
choco upgrade -y visualstudio2017buildtools --package-parameters "--add Microsoft.VisualStudio.Workload.VCTools --includeRecommended"
```

(the package passes nearly all package parameters directly to the VS installer, so the official Microsoft documentation applies: https://docs.microsoft.com/en-us/visualstudio/install/use-command-line-parameters-to-install-visual-studio?view=vs-2017)

The python2 package is completely unrelated, so if you want to install everything using only one choco package then you need to craft such a package yourself, for example by merging the install scripts of the existing packages. I'm not sure why you would need to do that, however - could you elaborate on why you cannot install two or more packages?

**Comment by refack** [comment]
I don't need the `python2` package specifically. AFAICT the VS installer can slipstream python and that should be good enough:
![image](https://user-images.githubusercontent.com/96947/48293960-8d5c8400-e44f-11e8-800e-8e2ba6e75e49.png)

For the node-core development we use python for build scaffolding, tooling and as a test harness.
Recently we started to use boxstarter to wrap everything together, [and it's tricky](https://github.com/nodejs/node/issues/23838). I was thinking that it's actually overkill if all we need is VC++, an SDK, python2, and G4W, and now they are all available as "Individual Components" in the VS installer. And that is we can do it all in one `choco` call we don't need boxstarter.

**Comment by refack** [comment]
P.S. thank you for you time and attention.
