### ISSUE TITLE
visual studio 2017 ERROR Exception calling "Start" with "0" argument(s): "The directory name is invalid"

### ISSUE THREAD

**Issue by jeremygaither** [jberezanski/ChocolateyPackages#59]
Receiving errors when installing visual studio 2017 professional or enterprise packages on Windows 10: `ERROR: Exception calling "Start" with "0" argument(s): "The directory name is invalid"`

I've attempted to uninstall the visualstudio2017-installer and retry the other packages, with no success.

```
Chocolatey v0.10.11 Business
Installing the following packages:
visualstudio2017professional
By installing you accept licenses for the packages.

visualstudio2017-installer v1.0.2
visualstudio2017-installer package files install completed. Performing other installation steps.
 The install of visualstudio2017-installer was successful.
  Software install location not explicitly set, could be in package or
  default install location if installer.

VisualStudio2017Professional v15.9.4.0
visualstudio2017professional package files install completed. Performing other installation steps.
File appears to be downloaded already. Verifying with package checksum to determine if it needs to be redownloaded.
Hashes match.
Virus checking skipped/turned off. Not verifying 'vs_professional.exe'
Hashes match.
Installing Visual Studio Installer...

ERROR: Exception calling "Start" with "0" argument(s): "The directory name is invalid"
The install of visualstudio2017professional was NOT successful.
Error while running 'C:\ProgramData\chocolatey\lib\VisualStudio2017Professional\tools\ChocolateyInstall.ps1'.
 See log for details.
visualstudio2017professional not installed. An error occurred during installation:
 Stopping further execution as visualstudio2017professional has failed install.
This is try 1/3. Retrying after 300 milliseconds.
 Error converted to warning:
 Could not find a part of the path 'C:\ProgramData\chocolatey\lib\VisualStudio2017Professional\.chocolateyPending'.
This is try 2/3. Retrying after 400 milliseconds.
 Error converted to warning:
 Could not find a part of the path 'C:\ProgramData\chocolatey\lib\VisualStudio2017Professional\.chocolateyPending'.
Maximum tries of 3 reached. Throwing error.
Could not find a part of the path 'C:\ProgramData\chocolatey\lib\VisualStudio2017Professional\.chocolateyPending'.
```

I've posted a log: https://gist.github.com/jeremygaither/a4436dca6c195bca4ac4f563a40b97ea

**Comment by jberezanski** [comment]
The only thing I can think of that could possibly cause `Process.Start()` to throw an error like this is if the WorkingDirectory property was set to an invalid value.
My code sets WorkingDirectory to the value of Get-Location (same as the original Chocolatey helper Start-ChocolateyProcessAsAdmin.ps1). I'm guessing in your environment Get-Location returns an unexpected value.

Could you please do the following:
- open C:\ProgramData\Chocolatey\extensions\chocolatey-visualstudio\Start-VSChocolateyProcessAsAdmin.ps1 in a text editor with administrative rights
- change line 100 from
```
  $process.StartInfo.WorkingDirectory = Get-Location
```
to
```
Write-Warning "Get-Location returns: [$(Get-Location)]"; $process.StartInfo.WorkingDirectory = "${Env:SystemDrive}\"
```
- run `cinst -y visualstudio2017professional` and post chocolatey.log

**Comment by jeremygaither** [comment]
This suddenly started working, with no apparent changes on my end. This was also occurring on other packages, so is likely not specific to this package.

I did some testing, and this may have been caused by running chocolatey with the current folder set as either c:\windows\system32 or a UNC path. Changing the current working folder to c:\temp seems to allow chocolatey to work properly.

**Comment by jberezanski** [comment]
Ah yes, now that you mention it I recall seeing this error at my company when someone invoked a script containing `cinst` commands (unrelated to VS 2017) directly from a network share.

You could report this issue to https://github.com/chocolatey/choco and ask for changing the default WorkingDirectory from `Get-Location` to something predictable, such as `"${Env:SystemDrive}\"`.

Meanwhile, since I'm using my own copy of the affected function, I'll implement a workaround in the VS packages.
