### ISSUE TITLE
Missing visual studio 2019 remote tools

### ISSUE THREAD

**Issue by Digmaster** [jberezanski/ChocolateyPackages#68]
Visual studio 2017 remote tools are present in this repo, however it looks like your selection for visual studio 2019 is missing the remote tools.

The tools are present at https://visualstudio.microsoft.com/en/downloads/?q=remote%20tools

**Comment by jberezanski** [comment]
True. I kind of forgot about them when I initially created the main VS 2019 packages and did not have time to add them later.
Would you like to contribute with a pull request?

**Comment by jberezanski** [comment]
Package [implemented](https://github.com/jberezanski/ChocolateyPackages/tree/master/visualstudio2019-remotetools), awaiting being added as maintainer of https://chocolatey.org/packages/visualstudio2019-remotetools.

**Comment by jberezanski** [comment]
Meanwhile, [visualstudio2019-performancetools](https://chocolatey.org/packages/visualstudio2019-performancetools/16.0.29519.18100) is published and pending moderation.

**Comment by jberezanski** [comment]
[visualstudio2019-remotetools](https://chocolatey.org/packages/visualstudio2019-remotetools) is published and pending moderation.
