### ISSUE TITLE
the dotnet4.7.2 package no longer installs 4.7.2

### ISSUE THREAD

**Issue by rgl** [jberezanski/ChocolateyPackages#77]
the dotnet4.7.2 package no longer install dotnet 4.7.2, it now installs dotnet 4.8 due to the dependency on dotnetfx not being bounded to <4.8 I guess.

**Comment by jberezanski** [comment]
That is correct. Packages such as dotnet4.7.2, which are merely "tag"/"marker" packages, are limited in functionality due to the way dependencies work in Chocolatey.

If you want to install a specific version of the .NET Framework, you should install a specific version of the dotnetfx package.
