### ISSUE TITLE
Visual Studio 2017 Workload vctools installation error

### ISSUE THREAD

**Issue by annsk** [jberezanski/ChocolateyPackages#80]
I have a problem with installation of package visualstudio2017-workload-vctools. 

It's fragment of log containing error: `ERROR: The remote file either doesn't exist, is unauthorized, or is forbidden for url 'https://aka.ms/vs/15/release/channel'`
[error.log](https://github.com/jberezanski/ChocolateyPackages/files/3871352/error.log)

Other packages were installed correctly. I use boxstarter and chocolatey. 

OS: Windows 10 Home 1909

**Comment by jberezanski** [comment]
This must have been a temporary problem either with your Internet connection or with the Microsoft servers (less likely). That address is correct (you can test it even from a web browser; it leads to a json text file named VisualStudio.15.Release.chman).

**Comment by jberezanski** [comment]
Closed due to lack of activity.
