### ISSUE TITLE
Unable to add component Microsoft.Net.Component.4.TargetingPack

### ISSUE THREAD

**Issue by amitechno** [jberezanski/ChocolateyPackages#83]
I want to download Microsoft.Net.Component.4.TargetingPack with this pack. I have tried
choco install visualstudio2017-workload-manageddesktopbuildtools --package-parameters "--includeRecommended" "--add Microsoft.Net.Component.4.TargetingPack" "--includeOptional"
what should be the way to install required component?

**Comment by jberezanski** [comment]
I want to make sure I understand correctly - do you want to add the .NET 4 targeting pack to an installation of VS 2017 Build Tools?

If yes, `choco install visualstudio2017-workload-manageddesktopbuildtools --package-parameters "--includeRecommended --includeOptional"` (note the quotes, only a single pair!) will install all components of the Managed Desktop Build Tools workload, including that targeting pack. This will work provided that 1) VS 2017 Build Tools is installed, 2) the Managed Desktop workload has not been installed yet.
