### ISSUE TITLE
Cannot install visualstudio2017buildtools

### ISSUE THREAD

**Issue by matthewtberry** [jberezanski/ChocolateyPackages#88]
Installation of `visualstudio2017buildtools` fails in a container based off [Windows Server Core](https://hub.docker.com/_/microsoft-windows-servercore), tag `ltsc2016-amd64`.  Docker running on Windows Server 2016.

`choco install visualstudio2017buildtools -y` results in checksum failure:

```
ERROR: Checksum for 'C:\Users\ContainerAdministrator\AppData\Local\Temp\chocolatey\visualstudio2017buildtools\15.9.21.0\vs_BuildTools.exe' did not meet '2331CAE21632689B1B4D4418DA67B7B490B661D0BB195AFFBFAE15927BC696B8' for checksum type 'SHA256'.
Consider passing the actual checksums through with --checksum --checksum64 once you validate the checksums are appropriate.
A less secure option is to pass --ignore-checksums if necessary.
The install of visualstudio2017buildtools was NOT successful.
```

Even if I pass `--ignore-checksums`, the installer fails with no clear indication why other than `vs_BuildTools.exe` exited with code `-2147024770`, including in the logs.

```
ERROR: Running ["C:\Users\ContainerAdministrator\AppData\Local\Temp\chocolatey\visualstudio2017buildtools\15.9.21.0\vs_BuildTools.exe" --quiet --norestart --wait] was not successful. Exit code was '-2147024770'. See log for possible error messages.
The install of visualstudio2017buildtools was NOT successful.
Error while running 'C:\ProgramData\chocolatey\lib\visualstudio2017buildtools\tools\ChocolateyInstall.ps1'.
See log for details.
```

**Comment by jberezanski** [comment]
The checksum in the 15.9.21.0 package is correct and matches the file at that url:
```
    -Url 'https://download.visualstudio.microsoft.com/download/pr/dd3eb7bc-5549-45f2-be9a-80984f4d4d90/2331cae21632689b1b4d4418da67b7b490b661d0bb195affbfae15927bc696b8/vs_BuildTools.exe' `
    -Checksum '2331CAE21632689B1B4D4418DA67B7B490B661D0BB195AFFBFAE15927BC696B8' `
```

If the installer gets corrupted somehow during download to your container, the failure is not surprising. You may look in the VS installer log files (`%TEMP%\chocolatey\dd_*.log`) to determine the exact cause.

**Comment by jberezanski** [comment]
-2147024770, or 0x8007007E, translates to ERROR_MOD_NOT_FOUND, "The specified module could not be found". So a DLL is missing or not registered properly. This may indicate many things:
- corruption of the container base image;
- corruption of the downloaded VS installer (very likely);
- reboot required by some software/OS update installed earlier in the container (rebooting is not supported by Windows containers; one needs to use a base image which already contains that software, e.g. specific .NET version);
- lack of some operating system features in the container (Microsoft does officially support installing the Build Tools in a container, but a different base image might be required).

Please note that I'm shooting in the dark here; I don't use containers and I have never tried to install the Build Tools in one.

**Comment by matthewtberry** [comment]
Thanks for the responses.  I changed the container base image to the latest 4.8 [.NET Framework SDK image](https://hub.docker.com/_/microsoft-dotnet-framework-sdk) and `visualstudio2017buildtools` installation succeeds.
