### ISSUE TITLE
visualstudio2019buildtools does not appear to add workloads when --package parameters "add" is provided

### ISSUE THREAD

**Issue by Pxtl** [jberezanski/ChocolateyPackages#93]
I've been executing 

```ps
choco install visualstudio2019buildtools -y `
    --package-parameters "--add Microsoft.VisualStudio.Workload.MSBuildTools --add Microsoft.VisualStudio.Workload.NetCoreBuildTools --add Microsoft.VisualStudio.Workload.WebBuildTools --add Microsoft.VisualStudio.Component.SQL.SSDTBuildSku --includeRecommended --includeOptional" `
    --force
```

and then reviewing the 

`C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\MSBuild\Microsoft\VisualStudio\v16.0`

folder and checking with vs_installer and not finding any of the requested components.

**Comment by Pxtl** [comment]
exported config from my buildtools:

```json
{
  "version": "1.0",
  "components": [
    "Microsoft.VisualStudio.Component.Roslyn.Compiler",
    "Microsoft.Component.MSBuild",
    "Microsoft.VisualStudio.Component.CoreBuildTools",
    "Microsoft.VisualStudio.Workload.MSBuildTools"
  ]
}
```

**Comment by jberezanski** [comment]
It worked for me just now (on a clean Windows Server 2012 R2 with choco 0.10.15). I copied the command from your post and pasted it in an admin PowerShell window. All workloads and components were installed.

Could you share these log files:
`$Env:ProgramData\Chocolatey\logs\chocolatey.log`
`$Env:TEMP\chocolatey\dd_bootstrapper_*.log`
`$Env:TEMP\chocolatey\dd_client_*.log`
`$Env:TEMP\chocolatey\dd_service_*.log`
`$Env:TEMP\chocolatey\dd_setup_*.log`
`$Env:TEMP\chocolatey\dd_setup_*.log`
`$Env:TEMP\chocolatey\dd_vs_BuildTools_decompression_log.txt`
?

**Comment by Pxtl** [comment]
Found it was being caused by the installer itself - something was timing out.  I was running this in the middle of a huge batch script and it wasn't logging errors properly.  Still can't figure out what's going on but it looks like it's command-line vs installer itself and not the choco package.  

Sorry, my bad.

**Comment by jberezanski** [comment]
The VS installer does feel somewhat brittle, at least in my experience, especially regarding timeouts/transient network errors (when testing on rather slow virtual machines, I struggled to get anything installed at all - even though the installation proceeded, the VS installer would become impatient and prematurely signal a failure).
That is why I adopted the habit of installing workloads one by one, in separate `choco` invocations, using the workload packages.

**Comment by jberezanski** [comment]
Closing as this seems to be an issue in the VS Installer.

**Comment by benh57** [comment]
I"m seeing this same issue. In my case, it's not an issue with the installer, chocolatey is passing 'update' instead of 'modify' or 'install', which causes the installer to ignore the --add. continuing to debug before writing a new issue.

**Comment by jberezanski** [comment]
That is expected. If a Build Tools instance is already installed, updating the `visualstudio2019buildtools` package will result in the "update" command being sent to the VS Installer in order to update the instance to the newest version. It is unfortunate that the VS Installer ignores --add/--remove in this case, but that was Microsoft's decision.

You can, however, use the workload packages (`visualstudio2019-workload-vctools` etc) to add workloads to an already installed VS instance.

**Comment by benh57** [comment]
I'm seeing this with the 'pro' version as well, not just buildtools.  The workload packages require the buildtools, not pro.

I think it would be nice if the choco pkgs would be smart enough to use 'modify' if -add is passed in the custom arguments.

**Comment by benh57** [comment]
Actually my real issue may be somewhat different. Having a mess of a time getting all systems to install both 14.28.29333 and 14.28.29910 MSVC. What a pain. :)
