### ISSUE TITLE
Internalize fails for KB3118401

### ISSUE THREAD

**Issue by OraDotNetDev** [jberezanski/ChocolateyPackages#94]
Hi Jakub

Would it be possible to drop the unofficial Windows 8 support from [KB3118401](https://github.com/jberezanski/ChocolateyPackages/blob/master/KB3118401/Tools/ChocolateyInstall.ps1)

The placeholder URL for the 32-bit Win 8 Package causes the internalize process to fail (when using Choco for Business.) This is because the Internalize process throws an error because it's not possible to download the non-existent URL.

Another user has previously run into this issue, and mentioned it on this [comment](https://chocolatey.org/packages/KB3118401#comment-4946705031) on the Community feed,

Thanks

ODN

```
Download of 'Windows6.1-KB3118401-x64.msu' completed.
Replacing 'https://download.microsoft.com/download/D/1/0/D107EB4D-2295-4127-A187-97FB290D7A3F/Windows6.1-KB3118401-x64.msu' with '$(Split-Path -parent $MyInvocation.MyCommand.Definition)\files\Windows6.1-KB3118401-x64.msu'

Download of 'Windows6.1-KB3118401-x64.msu' completed.
Replacing 'https://download.microsoft.com/download/E/6/5/E658276A-0ADF-439B-A63F-7E60C60728B6/Windows6.1-KB3118401-x64.msu' with '$(Split-Path -parent $MyInvocation.MyCommand.Definition)\files\7\Windows6.1-KB3118401-x64.msu'
Encountered error downloading package KB3118401 v:
System.Exception: The remote file either doesn't exist, is unauthorized, or is forbidden for url 'https://download.microsoft.com/not/available/Windows8-RT-KB3118401-x86.msu'.
  The remote server returned an error: (404) Not Found...
```

**Comment by jberezanski** [comment]
https://chocolatey.org/packages/KB3118401/1.0.5

**Comment by jberezanski** [comment]
Yes, I see no reason for keeping up partial Windows 8 support if it causes problems somewhere.

**Comment by OraDotNetDev** [comment]
Afternoon Jakub,

Thanks very much for sorting this out so quickly, I really appreciate it 😁

ODN
